version: "3.9"

services:
  discord-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./bot:/app

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./bot:/app
      - ./tests:/app/tests
    env_file: .env.test
    command: ["python", "/app/tests/dev_test.py"]

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./bot/characters:/app/characters:ro
    environment:
      - CHARACTER_DIR=/app/characters

