FROM python:3.11-slim

WORKDIR /app
COPY bot/ /app
COPY tests/ /app/tests/
COPY .env.tests /app/.env
RUN pip install --no-cache-dir -r requirements.txt

ENV CHARACTER_DIR=/app/tests/test_characters
ENV PYTHON_PATH=.

CMD ["pytest"]